## 卷积操作

In [1]:
import torch

inp = torch.tensor([[1, 2, 0, 3, 1],
                    [0, 1, 2, 3, 1],
                    [1, 2, 1, 0, 0],
                    [5, 2, 3, 1, 1],
                    [2, 1, 0, 1, 1]]).reshape((1, 1, 5, 5))

kernel = torch.tensor([[1, 2, 1],
                       [0, 1, 0],
                       [2, 1, 0]]).reshape((1, 1, 3, 3))
print(inp.shape, kernel.shape)

torch.Size([1, 1, 5, 5]) torch.Size([1, 1, 3, 3])


### stride 
- 卷积核按照 stride 大小进行向右或向下的移动


**输入图像 (5x5)**

$$
\begin{bmatrix}
1 & 2 & 0 & 3 & 1 \\
0 & 1 & 2 & 3 & 1 \\
1 & 2 & 1 & 0 & 0 \\
5 & 2 & 3 & 1 & 1 \\
2 & 1 & 0 & 1 & 1 \\
\end{bmatrix}
$$

**卷积核 (3x3)**

$$
\begin{bmatrix}
1 & 2 & 1 \\
0 & 1 & 0 \\
2 & 1 & 0 \\
\end{bmatrix}
$$

**当 Stride = 1 卷积计算如下**

$$
\begin{bmatrix}
1 & 2 & 0 \\
0 & 1 & 2 \\
1 & 2 & 1 
\end{bmatrix}
\odot
\begin{bmatrix}
1 & 2 & 1 \\
0 & 1 & 0 \\
2 & 1 & 0 \\
\end{bmatrix} \\ 
=\text{sum}(A \odot B) = \sum_{i=1}^{3} \sum_{j=1}^{3} (a_{ij} \cdot b_{ij})
$$
$$
A_{11} = 1 + 4 + 0 + 0 + 1 + 0 + 2 + 2 + 0 = 10
$$

**卷积后的输出**

$$
A =
\begin{bmatrix}
10 & 12 & 12 \\
18 & 16 & 16 \\
13 & 9 & 3 \\
\end{bmatrix}
$$


**当 Stride = 2 卷积结果如下**
$$
A =
\begin{bmatrix}
10 & 12 \\
13 & 3 \\
\end{bmatrix}
$$


In [10]:
import torch.nn.functional as F


out_stride = F.conv2d(inp, kernel, stride=1)
print("stride = 1 时，结果为：\n", out_stride)

print()
out_stride2 = F.conv2d(inp, kernel, stride=2)
print("stride = 2 时，结果为：\n", out_stride2)

stride = 1 时，结果为：
 tensor([[[[10, 12, 12],
          [18, 16, 16],
          [13,  9,  3]]]])

stride = 2 时，结果为：
 tensor([[[[10, 12],
          [13,  3]]]])


### padding

- 相当于在原矩阵上再加上套上一个值为 0 的数

**输入图像 (5x5)**

$$
\begin{bmatrix}
1 & 2 & 0 & 3 & 1 \\
0 & 1 & 2 & 3 & 1 \\
1 & 2 & 1 & 0 & 0 \\
5 & 2 & 3 & 1 & 1 \\
2 & 1 & 0 & 1 & 1
\end{bmatrix}
$$

**当 padding = 1 时 (6x6)**

$$
\begin{bmatrix}
0 & 0 & 0 & 0 & 0 & 0 & 0 \\
0 & 1 & 2 & 0 & 3 & 1 & 0 \\
0 & 0 & 1 & 2 & 3 & 1 & 0 \\
0 & 1 & 2 & 1 & 0 & 0 & 0 \\
0 & 5 & 2 & 3 & 1 & 1 & 0 \\
0 & 2 & 1 & 0 & 1 & 1 & 0 \\
0 & 0 & 0 & 0 & 0 & 0 & 0
\end{bmatrix}
$$

**卷积核 (3x3)**

$$
\begin{bmatrix}
1 & 2 & 1 \\
0 & 1 & 0 \\
2 & 1 & 0 \\
\end{bmatrix}
$$

**卷积计算结果如下**
$$
\begin{bmatrix}
1 &  3 &  4 & 10 & 8 \\
5 & 10 & 12 & 12 & 6 \\
7 & 18 & 16 & 16 & 8 \\
11 & 13 & 9 &  3 & 4 \\
14 & 13 & 9 &  7 & 4
\end{bmatrix}
$$

In [3]:
out_padding = F.conv2d(inp, kernel, stride=1, padding=1)
print(out_padding)

tensor([[[[ 1,  3,  4, 10,  8],
          [ 5, 10, 12, 12,  6],
          [ 7, 18, 16, 16,  8],
          [11, 13,  9,  3,  4],
          [14, 13,  9,  7,  4]]]])
